# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MYSQL_USER: utilisateur
      MYSQL_PASSWORD: utilisateur
      MYSQL_DATABASE: exemple
    volumes:
        - ./sql/install.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080