services:
  mymongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: my_flask_app_db
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    networks:
      - default

  mongoui:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mymongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mymongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - default
