# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: exercice
    volumes:
        - ./sql/install.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - 3306:3306

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080